name: famz
description: "Wake up smiling not snoozing"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^18.0.1
  uuid: ^4.3.3
  web: ^1.1.1
  timezone: ^0.10.0

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3

  # Navigation
  go_router: ^10.1.2

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Functional Programming
  dartz: ^0.10.1

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.1.0

  # Network
  http: ^1.1.0
  connectivity_plus: ^5.0.1
  http_parser: ^4.0.2

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Permissions
  permission_handler: ^10.0.0

  # Media & Recording
  audio_waveforms: ^1.0.5
  camera: ^0.10.5+5
  video_player: ^2.4.7
  audioplayers: ^6.5.0

  # record: ^4.4.4
  just_audio: ^0.9.34
  flutter_sound: ^9.2.13

  # JSON
  json_annotation: ^4.8.1

  # Utils
  intl: ^0.19.0
  path_provider: ^2.0.11
  image_picker: ^1.1.2
  share_plus: ^7.1.0
  timeago: ^3.7.1

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/"